# Generated by Django 5.2.17 on 2026-09-08 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inspire_id", models.BigIntegerField(unique=True)),
                ("title", models.TextField()),
                ("abstract", models.TextField()),
                (
                    "authors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("arxiv_id", models.CharField(blank=True, default="", max_length=64)),
                ("doi", models.CharField(blank=True, default="", max_length=128)),
                ("journal", models.CharField(blank=True, default="", max_length=256)),
                ("earliest_date", models.CharField(blank=True, default="", max_length=10)),
                ("citation_count", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "paper",
                "verbose_name_plural": "papers",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("abstract", ""), _negated=True),
                        name="paper_abstract_not_empty",
                    )
                ],
            },
        ),
    ]
