# Generated by Django 5.2.17 on 2026-09-09 12:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.SearchVector(
                        "title", config="english", weight="A"
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "abstract", config="english", weight="B"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="paper",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="paper_search_vector_gin"
            ),
        ),
    ]
