# Generated by Django 5.2.17 on 2026-09-14 14:44

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("papers", "0003_enable_vector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="embedded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="embedding_model",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
